config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'questions#index'

  resources :questions do
    resources :answers, shallow: true do
      patch :make_best, on: :member
    end
  end

  resources :attachments, only: :destroy
  resources :awards, only: :index
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  has_many :links, dependent: :destroy, as: :linkable
  has_many_attached :files

  belongs_to :question
  belongs_to :user

  validates :body, presence: true

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  default_scope { order(best: :desc) }

  def make_best!
    transaction do
      question.answers.where.not(id: id).update_all(best: false)
      question.award&.update!(user: user)
      update!(best: true)
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/award.rb
# frozen_string_literal: true

class Award < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :question

  validates :title, presence: true
  validates :url,
            format: { with: %r{https?://[\w.]+}i },
            presence: true
end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true

  validates :title, presence: true
  validates :url,
            format: { with: %r{https?://[\w.]+}i },
            presence: true
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :user

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_one  :award, dependent: :destroy
  has_many_attached :files
  accepts_nested_attributes_for :award, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions, dependent: :destroy
  has_many :answers,   dependent: :destroy
  has_many :awards

  def author_of?(resource)
    id.present? &&
      resource.respond_to?(:user_id) &&
      id == resource&.user_id
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_answer, only: %i[update make_best destroy]
  before_action :check_answer_permissions, only: %i[update destroy]
  before_action :check_question_permissions, only: %i[make_best]

  def create
    @question = Question.find(params[:question_id])
    @answer   = @question.answers.create(answer_params.merge(user: current_user))
  end

  def update
    @answer.update(answer_params)
  end

  def make_best
    @answer.make_best!
  end

  def destroy
    @answer.destroy
  end

  private

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def check_answer_permissions
    render_403 unless current_user.author_of?(@answer)
  end

  def check_question_permissions
    render_403 unless current_user.author_of?(parent_question)
  end

  def parent_question
    @parent_question ||= @answer.question
  end

  def render_403
    send_file File.join(Rails.root, 'public/403.html'),
              type: 'text/html; charset=utf-8',
              status: :forbidden
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[id title url _destroy])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/attachments_controller.rb
# frozen_string_literal: true

class AttachmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_attachment
  before_action :load_model
  before_action :check_permissions

  def destroy
    @attachement_id = @attachment.id
    @attachment.destroy
  end

  private

  def load_attachment
    @attachment = ActiveStorage::Attachment.find(params[:id])
  end

  def load_model
    @model = @attachment.record
  end

  def check_permissions
    render_403 unless current_user.author_of?(@model)
  end

  def render_403
    render file: File.join(Rails.root, 'public/403.html'),
           status: :forbidden,
           layout: false
  end
end

app/controllers/awards_controller.rb
# frozen_string_literal: true

class AwardsController < ApplicationController
  before_action :authenticate_user!

  def index
    @questions = current_user.awards
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, except: %i[index new create]
  before_action :check_user_permissions, except: %i[index new show create]

  def index
    @questions = Question.all
  end

  def new
    @question = current_user.questions.new
    @question.award = Award.new
    @question.links.build
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def show
    @answer = @question.answers.new
    @answer.links.build
  end

  def update
    @question.update(question_params)
  end

  def destroy
    if @question.destroy
      redirect_to questions_path, notice: 'Your question was successfully removed.'
    else
      redirect_to @question
    end
  end

  private

  def check_user_permissions
    return if current_user.author_of?(@question)

    send_file File.join(Rails.root, 'public/403.html'),
              type: 'text/html; charset=utf-8',
              status: :forbidden
  end

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question)
          .permit(:title, :body,
                  files: [],
                  links_attributes: %i[id title url _destroy],
                  award_attributes: %i[id title url _destroy])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/answers/_answer.html.slim
- if answer&.body&.present?
    .answer id="answer-#{answer.id}"
      .body
        = answer.body
      .links
        =render answer.links
      .attachments
        = render partial: "attachments/attachment", collection: answer.files
      - if current_user&.author_of?(answer.question)
        - if answer.best?
          .best_answer_mark The best answer!
        - else
          = link_to 'Make best', make_best_answer_path(answer), class: 'make-best-answer-link', method: :patch, remote: true
      - if current_user&.author_of?(answer)
        = link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
        = link_to 'Delete answer', answer, remote: true, method: :delete
      = form_with model: answer, remote: true, class: 'hidden', html: { id: "edit-answer-#{answer.id}" }  do |f|
        = f.text_area :body, rows: 3
        = f.label :files
        = f.file_field :files, multiple: true
        = render 'links/links_form', resource: f
        = f.submit 'Save'

app/views/answers/_form.html.slim
- if current_user
  .answer_form
    .answer_errors
      = render 'shared/errors', resource: @answer
    = form_with model: [@question, @answer], remote: true do |f|
      = f.text_area :body, rows: 3
      = render 'links/links_form', resource: f
      = f.label :files
      = f.file_field :files, multiple: true
      = f.submit 'answer'

app/views/answers/create.js.erb
$('.answer_errors').html("<%= render 'shared/errors', resource: @answer %>");

<% if @answer.persisted? %>
  $('.notice').html("Your answer was successfully created.");
  $('.answers').append("<%= j render @answer %>");
  $('#answer_body').val("");
<% else %>
  $('.notice').html("");
<% end %>

app/views/answers/destroy.js.erb
$('.notice').html("Your answer was successfully removed.");
$('<%= "#answer-#{@answer.id}" %>').remove();

app/views/answers/make_best.js.erb
$('.notice').html("The answer was marked as best.");
$('.answers').html("<%= j render @parent_question.answers %>");

app/views/answers/update.js.erb
$('.answer_errors').html("<%= render 'shared/errors', resource: @answer %>");

<% if @answer.errors.present? %>
  $('.notice').html("");
<% else %>
  $('.notice').html("Your answer was successfully edited.");
  $('<%= "#answer-#{@answer.id}" %>').html("<%= j render @answer %>");
  $("form#edit-answer-<%= @answer.id %>").addClass('hidden');
<% end %>

app/views/attachments/_attachment.html.slim
p.attachment id="attachment-#{attachment.id}"
  = link_to attachment.filename.to_s, url_for(attachment)
  - if current_user&.author_of?(attachment.record)
    = link_to 'Remove', attachment_path(attachment), remote: true, method: :delete

app/views/attachments/destroy.js.erb
$('.notice').html("Attachment was successfully removed.");
$('<%= "#attachment-#{@attachement_id}" %>').remove();

app/views/awards/_award.html.slim
p.award id="award-#{award.id}"
  .question_title
    = award.question.title
  .title
    = award.title
  .image
    = image_tag(award.url)

app/views/awards/_award_form.html.slim
.award_fields
  = resource.fields_for :award do |award|
    = award.label :title, 'Award title'
    = award.text_field :title
    = award.label :url
    = award.text_field :url

app/views/awards/index.html.slim
= render current_user.awards

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qna</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <%= link_to :logout, destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to :login, new_user_session_path %>
    <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/links/_link.html.slim
p.link id="link-#{link.id}"
  = link_to link.title, link.url
  -if /gist\.github/.match(link.url)
    == "<script src=\"#{link.url}.js\"></script>"

app/views/links/_link_fields.html.slim
.nested-fields
  .field
    = f.label :title, 'Link title'
    = f.text_field :title
  .field
    = f.label :url
    = f.text_field :url
  .field
  = link_to_remove_association "remove link", f

app/views/links/_links_form.html.slim
.link_fields
  = resource.fields_for :links do |link|
    = render 'links/link_fields', f: link
  .links
    = link_to_add_association 'add link', resource, :links, partial: 'links/link_fields'

app/views/questions/_form.html.slim
= render 'shared/errors', resource: @question
= form_with model: @question, local: true do |f|
  = f.label :title
  = f.text_field :title
  = f.label :body
  = f.text_area :body
  = f.label :files
  = f.file_field :files, multiple: true
  = render 'awards/award_form', resource: f
  = render 'links/links_form', resource: f
  = f.submit :create

app/views/questions/_question.html.slim
.question
  h1= @question.title
  p= @question.body

  #award
    - if @question.award
      = render @question.award

  .attachments
    = render partial: "attachments/attachment", collection: @question.files

  .links
    = render question.links

  - if current_user&.author_of?(@question)
    = link_to 'Edit', '#', class: 'edit-question-link', data: { question_id: question.id }
    = link_to 'Delete question', question_path(@question), method: :delete

  .question_errors
    = render 'shared/errors', resource: @question
  = form_with model: question, remote: true, class: 'hidden', html: {id: "edit-question-#{question.id}"}  do |f|
    = f.text_area :title
    = f.text_area :body, rows: 3
    = f.label :files
    = f.file_field :files, multiple: true
    = render 'links/links_form', resource: f
    = f.submit 'Save'

app/views/questions/edit.html.slim
= render 'form'

app/views/questions/index.html.slim
- @questions.each do |question|
  p= link_to question.title, question

p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= render 'form'

app/views/questions/show.html.slim
= render @question

= render 'answers/form'

.answers
  = render @question.answers

app/views/questions/update.js.erb
$('.question_errors').html("<%= render 'shared/errors', resource: @question %>");

<% if @question.errors.present? %>
  $('.notice').html("");
<% else %>
  $('.notice').html("Your question was successfully edited.");
  $('.question').html("<%= j render @question %>");
<% end %>

app/views/shared/_errors.html.slim
-if resource&.errors.present?
  b= "#{resource&.errors.count} error(s) detected:"
  ul
    -resource.errors.full_messages.each do |message|
      li= message